//*****************************************************************************
//
//! @file am_reg_iomstr_commands.h
//!
//! @brief Command Register macros for the IOMSTR module
//
//*****************************************************************************

//*****************************************************************************
//
// ${copyright}
//
// This is part of revision ${version} of the AmbiqSuite Development Package.
//
//*****************************************************************************
#ifndef AM_REG_IOMSTR_COMMANDS_H
#define AM_REG_IOMSTR_COMMANDS_H



#define AM_IOMSTR_CMD_CMD_S                          0
#define AM_IOMSTR_CMD_CMD_M                          0xFFFFFFFF

// the following were hand generated by dbaker from material originally hand generated by RH

//
// *************************************
// IOMSTR I2C command definitions
// *************************************
//      |31|30|29|28|27|26|25|24|23|22|21|20|19|18|17|16|15|14|13|12|11|10| 9| 8| 7| 6| 5| 4| 3| 2| 1| 0|
//  I2C |--OPER--|CT|LB|10|--------|-------ADDRESS------|------- OFFSET --------|-------- LENGTH -------|
//  SPI |--OPER--|CT|LB|--UPLNGTH--|-- Rsvd ---|--CHN---|Rv|---- OFFSET --------|-------- LENGTH -------|
//  OPER: Write: 000, Read 100, Write Raw 010, Read Raw 110 (bit30 indicates RAW, IOMSTR_CMD_RAW)
//  I2C CMD fields: OPER, CONT, LSB, 10BIT, ADDRESS (7 or 10 bits), OFFSET, LENGTH
//  SPI CMD fields: OPER, CONT, LSB, UPLNGTH, Rsvd, CHANNEL, Rsvd, OFFSET, LENGTH
//                  SPI length is 10 bits, [26:25][7:0].
//  ** SPI OFFSET is 7 bits (bit15 is RSVD), I2C OFFSET is 8 bits.
//
#define AM_IOMSTR_CMD_LENGTH_S         0
#define AM_IOMSTR_CMD_OFFSET_S         8
#define AM_IOMSTR_CMD_SPICHL_S         16
#define AM_IOMSTR_CMD_I2CADDR_S        16
#define AM_IOMSTR_CMD_I2CADDR10BIT_S   16
#define AM_IOMSTR_CMD_SPI_UPLNGTH_S    23
#define AM_IOMSTR_CMD_I2C10BIT_S       26
#define AM_IOMSTR_CMD_LSB_S            27
#define AM_IOMSTR_CMD_CONT_S           28
#define AM_IOMSTR_CMD_COMMAND_S        29
#define AM_IOMSTR_CMD_RAW_S            30

#define AM_IOMSTR_CMD_LENGTH_M         0xff
#define AM_IOMSTR_CMD_OFFSET_M         0xff
#define AM_IOMSTR_CMD_SPICHL_M         0x07
#define AM_IOMSTR_CMD_I2CADDR_M        0x7f
#define AM_IOMSTR_CMD_I2CADDR10BIT_M   0x3ff
#define AM_IOMSTR_CMD_SPI_UPLNGTH_M    0x07800000
#define AM_IOMSTR_CMD_I2C10BIT_M       0x1
#define AM_IOMSTR_CMD_LSB_M            0x1
#define AM_IOMSTR_CMD_CONT_M           0x1
#define AM_IOMSTR_CMD_COMMAND_M        0xe
#define AM_IOMSTR_CMD_RAW_M            0x1


#define AM_IOMSTR_CMD_SPI_UPLNGTH_GET(v)  ((v>>8)<<AM_IOMSTR_CMD_SPI_UPLNGTH_S)




#endif  // __IOMSTR_COMMANDS_H

